[proxmox]
pvehost ansible_host=10.2.0.253 ansible_user=root

[proxmox:vars]
ct_ids=402,403,404
ct_hostname_prefix=mcb2zo
ct_password=Minecraft123!
ct_cores=2
ct_memory=2048
ct_rootfs_gb=10
ct_bridge=vmbr0
ct_gateway=10.2.0.254
ct_ip_402=10.2.0.30
ct_ip_403=10.2.0.31
ct_ip_404=10.2.0.32
ct_nameserver=8.8.8.8
ct_template=local:vztmpl/debian-12-standard_12.12-1_amd64.tar.zst
ct_storage=local

[minecraft]
mc-402 ansible_host=10.2.0.30
mc-403 ansible_host=10.2.0.31
mc-404 ansible_host=10.2.0.32

[minecraft:vars]
ansible_user=root
ansible_password=Minecraft123!
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
